# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5613dc6e20ed437a1d37dc1297645d03873a2de7e0f7b1aca1e7467e1b094c2724b97e407b2c3070b8ee934ab5dddd37406cbb879cf4f77d804ea4657fd38094

test:
  secret_key_base: 211b58ff8f7e667fea690aa5989876e48800656384e48c550943520b54b4ead5fab3491b97080020da73aa4f1fc921e7f1a4f7beb56c31d0203e856951bd100c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
